// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Context$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Context";
  readonly sourceName: "contracts/Context.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Context.sol";
  readonly buildInfoId: "solc-0_8_7-bef2294aa5c0c811c8aabb1e7349397fd5348671";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Context"]: Context$Type;
    ["contracts/Context.sol:Context"]: Context$Type;
  }
}