// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeMath";
  readonly sourceName: "contracts/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cfdfafe6b85695910dbe71daa293c08f1841f9fe7e8ad5c17cc900739542f84664736f6c63430008070033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cfdfafe6b85695910dbe71daa293c08f1841f9fe7e8ad5c17cc900739542f84664736f6c63430008070033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_7-bef2294aa5c0c811c8aabb1e7349397fd5348671";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/SafeMath.sol:SafeMath"]: SafeMath$Type;
  }
}